### ISSUE TITLE
Missing TaiG App Store

### ISSUE THREAD

**Issue by neal** [p0sixspwn/p0sixspwn#1]
We r of want the TaiG Chinese App Store.

**Comment by guoye-zhang** [comment]
Nobody wants TaiG. It's full of malware, and bricks your device.

**Comment by akemin-dayo** [comment]
I'm... pretty sure he wasn't serious.

**Comment by ljzyal** [comment]
360派你来的吧，怎么哪里都有360这些败类

**Comment by ljzyal** [comment]
translate to English:
Fuck 360

**Comment by ieswxia** [comment]
Are you joking ? If you are serious,I am sure you are 360 member.
Fuck 360,fuck TaiG.
But chinese own jailbreak tool is appreciated.

**Comment by kirb** [comment]
:thumbsup: I updated my iOS 7 jailbreak and now I can't get taig any more :( At least I could get it on iOS 6 if p0sixspwn supported it.

**Comment by TheFighter** [comment]
The missing of TaiG is a feature and not a bug!

**Comment by AdiSai** [comment]
We are of #Helo. #Pls no TaiG as it is #Piraci.

**Comment by rhcp011235** [comment]
#we #want #piracy

**Comment by p0sixspwn** [comment]
There is no TaiG support planned.

**Comment by Harinlen** [comment]
Yes！No TaiG！

**Comment by yinshunming** [comment]
Chinese are everywhere from google plus to twitter...
