### ISSUE TITLE
How to compile the software in Linux

### ISSUE THREAD

**Issue by linux0ne** [p0sixspwn/p0sixspwn#2]
My PC is 64 bit ubuntu 12.04.

How to compile the software in Ubuntu ？？

**Comment by rhcp011235** [comment]
There are many issues with linux. 

There are many type def issues. I am not sure how it even compiles on windows.

**Comment by akemin-dayo** [comment]
Well... that's the thing.

It doesn't compile on Windows. :P

**Comment by rhcp011235** [comment]
Never did try. It has windows defines. I got past a few of the errors for linux. But, a lot of the other bins are not open source, example: untether and others.

**Comment by p0sixspwn** [comment]
No Linux support intended.
