### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by JeffResc** [p0sixspwn/p0sixspwn#6]
Crashes after reboot

**Comment by niknah** [comment]
Me too.  Using v1.0.7
Then I ran it a 2nd time and it said that my device wasn't supported.

Went back to p0sixspwn-v1.0.2  and it worked fine,  after a few reboots and white screens.

Have an iPod 4th gen 6.1.5

**Comment by wickedrailee** [comment]
The same thing happens on Windows. I wouldn't be surprised if it's one bug.
I took several goes at it with no luck: tried running it in compatibility mode, tried disabling Apple's startup entries, tried with a fresh copy of iOS. But is always crashes a few seconds after the 'rebooting device' status appears.

Is it possible to provide an old version of the binaries, p0sixspwn devs?

**Comment by niknah** [comment]
Here're some older ones...
http://www.iclarified.com/37176/where-to-download-p0sixspwn-from

**Comment by JeffResc** [comment]
Same here

**Comment by wickedrailee** [comment]
Thank you, the old versions worked :)

**Comment by mailinglists35** [comment]
@niknah thank you so much! after much looking at p0sixspwn process with sysinternals procmon witout success, i finally found this github issue (and issue #8 )
i have a 4s on 6.1.3 and p0sixspwn kept crashing at "performing magic" step with "memory could not be read" error.
it went fine with the previous version, 1.0.7.
using xp sp3 and itunes 10.7.0.21 in case someone finds this via google
