### ISSUE TITLE
Crash on Win8

### ISSUE THREAD

**Issue by llibbey** [p0sixspwn/p0sixspwn#7]
Running Windows 8.1 and iOS 6.1.5 on iPod Touch 4G. Even after several tries, all the program does is reboot the iPod; right after that, I get the message that p0sixspwn has stopped working.

Any fixes?

**Comment by svercl** [comment]
Have you tried running it in compatibility mode for Windows XP? (SP3)

**Comment by llibbey** [comment]
Just ran it how you said, worked flawlessly!
Thanks, psychopathrik!
